version: '3.8'

services:
  backend:
    build: ./whiteboard-backend
    ports:
      - "5959:5959"
    environment:
      - JWT_SECRET=your_super_secure_jwt_secret_key_change_this_in_production_12345
      - PORT=5959
      - NODE_ENV=production
    volumes:
      - backend_rooms:/app/rooms
      - backend_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5959/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./whiteboard-frontend
      args:
        - VITE_BACKEND_URL=http://localhost:5959
    ports:
      - "3000:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  backend_rooms:
  backend_uploads:
